/* Santamore registration pack — review site. Runs in the published page. */
(function () {
  'use strict';
  const PACK = window.PACK; // documents and form definitions, generated by build-web.js
  const stateEl = document.getElementById('pack-state');
  let STATE; try { STATE = JSON.parse(stateEl.textContent || '{}'); } catch (e) { STATE = {}; }
  STATE.fields = STATE.fields || {}; STATE.checks = STATE.checks || {}; STATE.drafts = STATE.drafts || {};
  let dirty = false, canPublish = null, artifactNs = null, downloadsNs = null, unsaved = {};

  const $ = (s, r) => (r || document).querySelector(s);
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const nav = $('#nav'), main = $('#main'), sheet = $('#sheet'), status = $('#status');
  const showEn = $('#show-en');
  try { showEn.checked = localStorage.getItem('santamore.showEn') === '1'; } catch (e) {}
  document.body.classList.toggle('show-en', showEn.checked);
  showEn.addEventListener('change', () => { document.body.classList.toggle('show-en', showEn.checked); try { localStorage.setItem('santamore.showEn', showEn.checked ? '1' : '0'); } catch (e) {} });

  // ---------- navigation ----------
  function route() { const h = location.hash.replace(/^#\/?/, ''); const [kind, id] = h.split('/'); return kind && id ? { kind, id } : { kind: 'form', id: PACK.forms[0].id }; }
  function renderNav() {
    const r = route();
    const item = (kind, d, i) => `<li><a href="#/${kind}/${d.id}" ${r.kind === kind && r.id === d.id ? 'aria-current="page"' : ''}><span class="num">${String(i + 1).padStart(2, '0')}</span><span>${esc(d.title)}</span></a></li>`;
    nav.innerHTML = `<h2>Za predaju Ministarstvu</h2><ul>${PACK.forms.map((d, i) => item('form', d, i)).join('')}</ul>
      <h2>Nacrti za usvajanje</h2><ul>${PACK.drafts.map((d, i) => item('draft', d, i)).join('')}</ul>`;
  }
  function closeNav() { $('#navpanel').classList.remove('open'); $('#scrim').hidden = true; }
  $('#menubtn').addEventListener('click', () => { $('#navpanel').classList.add('open'); $('#scrim').hidden = false; });
  $('#scrim').addEventListener('click', closeNav);
  nav.addEventListener('click', e => { if (e.target.closest('a')) closeNav(); });

  // ---------- fields ----------
  function fieldValue(id, def) { return Object.prototype.hasOwnProperty.call(STATE.fields, id) ? STATE.fields[id] : def; }
  function renderInline(text, form) {
    // {{id}} → field span; {{sig}} → signature line
    return text.replace(/\{\{(sig|[a-z0-9_]+)\}\}/g, (m, id) => {
      if (id === 'sig') return '<span class="sig" aria-label="potpis"></span>';
      const f = form.fields[id]; if (!f) return m;
      const v = fieldValue(id, f.value);
      const ph = /^\[.*\]$/.test(v.trim()) ? ' placeholder' : '';
      return `<span class="field${f.block ? ' block' : ''}${ph}" contenteditable="true" role="textbox" aria-label="${esc(f.label || id)}" data-field="${id}" spellcheck="false">${esc(v)}</span>`;
    });
  }
  function renderForm(form) {
    const legend = `<div class="legend"><span><span class="field">plavo</span> = popunjeno, klikni i izmijeni</span><span><span class="sig"></span> = potpis, ostaje prazno za štampu</span><span>☐ EN = prikaži prevod</span></div>`;
    const blocks = form.blocks.map(b => {
      const en = b.en ? `<div class="en">${b.en}</div>` : '';
      if (b.type === 'h') return `<div class="title">${renderInline(b.me, form)}</div>${b.en ? `<div class="en center">${b.en}</div>` : ''}`;
      if (b.type === 'h3') return `<h3>${esc(b.me)}</h3>${b.en ? `<div class="en">${esc(b.en)}</div>` : ''}`;
      if (b.type === 'h2') return `<h2>${esc(b.me)}</h2>${b.en ? `<div class="en">${esc(b.en)}</div>` : ''}`;
      if (b.type === 'note') return `<div class="note noprint">${b.me}</div>`;
      if (b.type === 'sigrow') return `<div class="sigrow">${b.items.map(it => `<div>${renderInline(it.me, form)}<div class="lbl">${esc(it.lbl || '')}${it.en ? ' · ' + esc(it.en) : ''}</div></div>`).join('')}</div>`;
      if (b.type === 'list') return `<ol>${b.items.map(it => `<li>${renderInline(it, form)}</li>`).join('')}</ol>${en}`;
      if (b.type === 'check') { const done = !!STATE.checks[b.id]; return `<div class="check${done ? ' done' : ''}"><input type="checkbox" id="chk-${b.id}" data-check="${b.id}" ${done ? 'checked' : ''}><label for="chk-${b.id}">${renderInline(b.me, form)}</label></div>${en}`; }
      return `<p class="${b.cls || ''}">${renderInline(b.me, form)}</p>${en}`;
    }).join('');
    sheet.innerHTML = `<h1>${esc(form.title)}</h1><p class="sub">${esc(form.subtitle || '')}</p>${legend}${form.note ? `<div class="note noprint">${form.note}</div>` : ''}<div class="doc" id="doc">${blocks}</div>`;
    sheet.querySelectorAll('[data-field]').forEach(el => {
      el.addEventListener('input', () => {
        const id = el.dataset.field, v = el.innerText.replace(/\n{3,}/g, '\n\n');
        STATE.fields[id] = v; markDirty();
        el.classList.toggle('placeholder', /^\[.*\]$/.test(v.trim()));
        sheet.querySelectorAll(`[data-field="${id}"]`).forEach(o => { if (o !== el && o.innerText !== v) o.innerText = v; });
      });
      el.addEventListener('keydown', e => { if (e.key === 'Enter' && !el.classList.contains('block')) e.preventDefault(); });
      el.addEventListener('paste', e => { e.preventDefault(); document.execCommand('insertText', false, (e.clipboardData || window.clipboardData).getData('text')); });
    });
    sheet.querySelectorAll('[data-check]').forEach(el => el.addEventListener('change', () => { STATE.checks[el.dataset.check] = el.checked; el.closest('.check').classList.toggle('done', el.checked); markDirty(); }));
  }
  function renderDraft(d) {
    const html = STATE.drafts[d.id] ? sanitize(STATE.drafts[d.id]) : d.html;
    sheet.innerHTML = `<h1>${esc(d.title)}</h1><p class="sub">${esc(d.subtitle || '')}</p><div class="note noprint">Nacrt je moguće mijenjati direktno u tekstu. <b>Crnogorski je mjerodavan tekst</b>; engleski prevod ispod svakog člana prikazuje se uz opciju EN. Sačuvaj za tim objavljuje izmjene svima.</div><div class="doc draft" id="doc" contenteditable="true" spellcheck="false">${html}</div>`;
    const doc = $('#doc'); let t;
    doc.addEventListener('input', () => { clearTimeout(t); t = setTimeout(() => { STATE.drafts[d.id] = doc.innerHTML; markDirty(); }, 400); });
  }
  function sanitize(html) {
    const tpl = document.createElement('template'); tpl.innerHTML = html;
    tpl.content.querySelectorAll('script,style,iframe,object,embed,link,meta').forEach(n => n.remove());
    tpl.content.querySelectorAll('*').forEach(n => { [...n.attributes].forEach(a => { if (/^on/i.test(a.name) || (a.name === 'href' && /^\s*javascript:/i.test(a.value)) || a.name === 'srcdoc') n.removeAttribute(a.name); }); });
    return tpl.innerHTML;
  }
  function render() {
    const r = route(); renderNav();
    const d = r.kind === 'draft' ? PACK.drafts.find(x => x.id === r.id) : PACK.forms.find(x => x.id === r.id);
    if (!d) { location.hash = '#/form/' + PACK.forms[0].id; return; }
    document.title = d.title + ' · Santamore';
    if (r.kind === 'draft') renderDraft(d); else renderForm(d);
    main.scrollTo({ top: 0 }); window.scrollTo({ top: 0 });
  }
  window.addEventListener('hashchange', render);

  // ---------- saving (republish the page with the state embedded) ----------
  function markDirty() { dirty = true; setStatus('Izmjene nisu sačuvane za tim', 'warn'); $('#save').disabled = canPublish === false; }
  function setStatus(t, cls) { status.textContent = t; status.className = 'status' + (cls ? ' ' + cls : ''); }
  function currentDocument() {
    // Regenerate the page from state: reset the rendered content, stamp the state, serialize, then restore.
    const savedHash = location.hash; const sheetHtml = sheet.innerHTML; const navHtml = nav.innerHTML;
    sheet.innerHTML = ''; nav.innerHTML = ''; closeNav();
    stateEl.textContent = JSON.stringify(STATE);
    const html = '<!doctype html>\n' + document.documentElement.outerHTML;
    sheet.innerHTML = sheetHtml; nav.innerHTML = navHtml; location.hash = savedHash;
    return html;
  }
  async function save() {
    if (!artifactNs) { setStatus('Čuvanje nije dostupno u ovom prikazu', 'warn'); return; }
    const btn = $('#save'); btn.disabled = true; setStatus('Čuvanje…');
    try { await artifactNs.publish(currentDocument()); dirty = false; setStatus('Sačuvano za tim', 'ok'); toast('Sačuvano. Svi koji otvore stranicu vide izmjene.'); }
    catch (e) {
      const code = e && e.code;
      if (code === 'not_writer' || code === 'not_granted') { canPublish = false; setStatus('Samo urednici mogu sačuvati za tim; izmjene ostaju samo u ovom prozoru', 'warn'); }
      else if (code === 'conflict') { setStatus('Neko drugi je sačuvao u međuvremenu; stranica se osvježava', 'warn'); }
      else { setStatus('Čuvanje nije uspjelo: ' + ((e && e.message) || code || 'greška'), 'warn'); btn.disabled = false; }
    }
  }
  $('#save').addEventListener('click', save);
  window.addEventListener('beforeunload', e => { if (dirty) { e.preventDefault(); e.returnValue = ''; } });

  // ---------- PDF and print ----------
  async function downloadPdf() {
    const r = route(); const d = (r.kind === 'draft' ? PACK.drafts : PACK.forms).find(x => x.id === r.id);
    const btn = $('#pdf'); btn.disabled = true; setStatus('Priprema PDF…');
    const hadEn = document.body.classList.contains('show-en');
    document.body.classList.add('pdfmode'); document.body.classList.toggle('show-en', $('#pdf-en').checked);
    sheet.querySelectorAll('[contenteditable]').forEach(el => el.setAttribute('contenteditable', 'false'));
    try {
      if (typeof html2pdf !== 'function') throw new Error('PDF biblioteka nije učitana');
      const blob = await html2pdf().set({ margin: [14, 14, 16, 14], filename: d.file + '.pdf', image: { type: 'jpeg', quality: 0.95 }, html2canvas: { scale: 2, useCORS: false, logging: false, backgroundColor: '#ffffff' }, jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }, pagebreak: { mode: ['css', 'legacy'] } }).from(sheet).outputPdf('blob');
      if (!downloadsNs) throw Object.assign(new Error('Preuzimanje nije dostupno u ovom prikazu'), { code: 'unavailable' });
      const res = await downloadsNs.save({ filename: d.file + '.pdf', data: blob });
      setStatus(res.status === 'saved' ? 'PDF sačuvan' : 'PDF isporučen', 'ok');
    } catch (e) {
      const code = e && e.code;
      setStatus(code === 'declined' ? 'Preuzimanje otkazano' : 'PDF nije uspio: ' + ((e && e.message) || code || 'greška'), 'warn');
    } finally {
      document.body.classList.remove('pdfmode'); document.body.classList.toggle('show-en', hadEn);
      sheet.querySelectorAll('[data-field],.draft').forEach(el => el.setAttribute('contenteditable', 'true'));
      btn.disabled = false;
    }
  }
  $('#pdf').addEventListener('click', downloadPdf);
  $('#print').addEventListener('click', () => { const hadEn = document.body.classList.contains('show-en'); document.body.classList.toggle('show-en', $('#pdf-en').checked); window.print(); document.body.classList.toggle('show-en', hadEn); });

  function toast(t) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = t; document.body.appendChild(el); setTimeout(() => el.remove(), 3200); }

  // ---------- capabilities (light up after load) ----------
  render();
  setStatus('Učitano');
  if (window.claude && typeof window.claude.use === 'function') {
    window.claude.use('artifact').then(ns => { artifactNs = ns; if (!ns) { canPublish = false; $('#save').disabled = true; $('#save').title = 'Čuvanje za tim nije dostupno u ovom prikazu'; } });
    window.claude.use('downloads').then(ns => { downloadsNs = ns; if (!ns) { $('#pdf').hidden = true; $('#pdf-hint').hidden = false; } });
  } else { $('#save').disabled = true; $('#pdf').hidden = true; $('#pdf-hint').hidden = false; }
})();
